# run: conda env create -f environment.yml
name: sarrender
channels:
  - defaults
  - nvidia
  - conda-forge
  - pytorch
  - iopath
  - pytorch3d
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - tqdm
  - numpy
  - click
  - pillow
  - scipy
  - iopath
  - pytorch3d
  - opencv
  - pip:
      - imageio
      - imageio-ffmpeg
